# Generated by Django 5.2.5 on 2025-09-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outflow',
            options={'ordering': ('-updated_at',)},
        ),
    ]
